vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.o.laststatus = 0
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = false
vim.o.wrap = true
vim.o.showcmd = true
vim.o.wildmenu = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.clipboard = 'unnamedplus'
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.autochdir = true
vim.o.scrolloff = 4
vim.o.smartindent = true
vim.o.updatetime = 200
vim.o.mouse = 'a'
vim.o.termguicolors = true
vim.o.winborder = 'rounded'
vim.o.fileencodings = 'utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1'
vim.o.encoding = 'utf8'
vim.o.swapfile = true
vim.o.undofile = true

vim.opt.iskeyword = '_,49-57,A-Z,a-z'
