[Appearance]
color_scheme_path=/etc/nixos/config/qt5ct/colors/noctalia.conf
custom_palette=true
standard_dialogs=default
style=Adwaita-Dark

[Fonts]
fixed="JetBrainsMono Nerd Font Mono,12,-1,5,400,0,0,0,0,0"
general="JetBrainsMono Nerd Font Mono,12,-1,5,400,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
dialog_buttons_have_icons=1
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
